[package]
name = "solana-usdc-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
solana-client = "2.3.7"
solana-sdk = "2.0"
solana-transaction-status = "2.0"
chrono = "0.4"
env_logger = "0.10"
log = "0.4"
